// Generated by https://quicktype.io

export interface IUserHistory {
  _id: string;
  title: string;
  author: string;
  returnDate?: string;
}

export interface IHistory {
  _id: string;
  bookId: string;
  userId: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  user: User;
  book: Book;
}

export interface IHistoryProps {
  _id: string;
  book: string;
  user?: string;
  status?: string;
  author?: string;
}

export interface Book {
  title: string;
  author: string;
  ISBN: string;
}

export interface User {
  name: string;
  email: string;
}

// Generated by https://quicktype.io
